resources:
  - name: src
    type: gitRepo
    repoPath: ranjithrs/app
    configuration:
      integrationName: ranjithrs_github
      branches:
        only: master
    version:
      sha: master

  - name: npmSrc
    type: file
    configuration:
      integrationName: art
    version:
      pattern: "npm-dev-local/"

  - name: bldInfo
    type: buildInfo
    version:
      buildName: native_pipeline
      buildNumber: 1

  - name: promotedBld
    type: buildInfo
    version:
      buildName: native_pipeline
      buildNumber: 1

pipelines:
  - name: native_pipeline
    steps:
      - name: dockerBuild
        type: build
        configuration:
          affinityGroup: root
        payloadType: docker
        setup:
          build:
            dockerFileLocation: .
            dockerFileName: Dockerfile
            imageName: 34.66.110.173:8081/docker-local/demo
            imageTag: $PIPELINE_NAME.$RUN_NUMBER
        requires:
          integrations:
            - art
            - notifySlack
          resources:
            - src
            - npmSrc
        execution:
          onSuccess:
            - send_notification notifySlack --text "built docker image 34.66.110.173:8081/docker-local/demo:$PIPELINE_NAME.$RUN_NUMBER"
          onFailure:
            - send_notification notifySlack --text "could not build docker image 34.66.110.173:8081/docker-local/demo:$PIPELINE_NAME.$RUN_NUMBER"


      - name: pushDockerImg
        type: push
        configuration:
          affinityGroup: root
        setup:
          push:
            targetRepo: docker-local
        requires:
          integrations:
            - art
            - notifySlack
        triggeredBy:
          steps:
            - dockerBuild
        execution:
          onSuccess:
            - send_notification notifySlack --text "pushed docker image 34.66.110.173:8081/docker-local/demo:$PIPELINE_NAME.$RUN_NUMBER"
          onFailure:
            - send_notification notifySlack --text "could not push docker image 34.66.110.173:8081/docker-local/demo:$PIPELINE_NAME.$RUN_NUMBER"


      - name: publishBldInfo
        type: publish
        configuration:
          affinityGroup: root
        requires:
          integrations:
            - art
            - notifySlack
        triggeredBy:
          steps:
            - pushDockerImg
        execution:
          onSuccess:
            - send_notification notifySlack --text "published build info for buildName=$dockerBuild_buildName buildNumber=$dockerBuild_buildNumber"
          onFailure:
            - send_notification notifySlack --text "could not publish buildName=$dockerBuild_buildName buildNumber=$dockerBuild_buildNumber"
        outputResources:
          - bldInfo

      - name: promoteBld
        type: promote
        configuration:
          affinityGroup: root
        setup:
          promote:
            targetRepo: demo
        requires:
          integrations:
            - art
            - notifySlack
        triggeredBy:
          resources:
            - bldInfo
        execution:
          onSuccess:
            - send_notification notifySlack --text "promoted buildName=$dockerBuild_buildName buildNumber=$dockerBuild_buildNumber to demo"
          onFailure:
            - send_notification notifySlack --text "could not promote buildName=$dockerBuild_buildName buildNumber=$dockerBuild_buildNumber to demo"
        outputResources:
          - promotedBld
